RazorHotelDB/Models/Room.cs
using System.ComponentModel.DataAnnotations;

namespace RazorHotelDB.Models
{
    public class Room
    {        
        public int RoomNr { get; set; }       
        public char Types { get; set; }        
        public double Pris { get; set; }
        public int HotelNr { get; set; }

        public Room()
        {

        }
        public Room(int nr, char types, double pris)
        {
            RoomNr = nr;
            Types = types;
            Pris = pris;
        }

        public Room(int nr, int hotelNr, char types, double pris) : this(nr, types, pris)
        {
            HotelNr = hotelNr;
        }

        public override string ToString()
        {
            return $"Room: {RoomNr}, HotelNr: {HotelNr}, Types: {Types}, Pris: {Pris}";
        }
    }
}

RazorHotelDB/Models/RoomType.cs
namespace RazorHotelDB.Models
{
    public enum RoomType
    {
        S,
        D,
        F
    }
}

RazorHotelDB/Pages/Rooms/DeleteRoom.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB.Interfaces;
using RazorHotelDB.Models;

namespace RazorHotelDB.Pages.Rooms
{
    public class DeleteRoomModel : PageModel
    {
        private IRoomService _roomService;
        private IHotelService _hotelService;
        [BindProperty]
        public Room Room { get; set; }
        public Hotel Hotel { get; set; }

        public DeleteRoomModel(IRoomService roomService, IHotelService hotelService)
        {
            _roomService = roomService;
            _hotelService = hotelService;
        }
        public async Task OnGetAsync(int hid, int rid)
        {
            Room = await _roomService.GetRoomFromIdAsync(rid, hid);
        }
        public async Task<IActionResult> OnPostAsync(int hid, int rid)
        {
            await _roomService.DeleteRoomAsync(rid, hid);
            return RedirectToPage("GetAllRooms");
        }
    }
}

RazorHotelDB/Pages/Rooms/GetAllRooms.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB.Interfaces;
using RazorHotelDB.Models;
using RazorHotelDB.Services;
using System.Reflection;

namespace RazorHotelDB.Pages.Rooms
{
    public class GetAllRoomsModel : PageModel
    {
        private IRoomService _roomService;
        private IHotelService _hotelService;

        //HotelNr only bind to @Model.HotelNr and then never used
        [BindProperty(SupportsGet = true)]
        public int HotelNr { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Navn { get; set; }
        public List<Hotel> Hotels { get; set; }
        public List<Room> Rooms { get; set; }
        public string UserName { get; set; }

        public GetAllRoomsModel(IRoomService roomService, IHotelService hotelService)
        {
            _roomService = roomService;
            _hotelService = hotelService;
            Hotels = new List<Hotel>();
        }

        public async Task OnGetMyRooms(int cid, string hname) {
            HotelNr = cid;
            Navn = hname;
            Rooms = await _roomService.GetAllRoomAsync(cid);
        }

        public async Task<IActionResult> OnGetAsync(int hid)
        {
            UserName = HttpContext.Session.GetString("UserName");
            if (UserName == null)
            {
                return RedirectToPage("/Login");
            }
            try
            {
                Hotels = await _hotelService.GetAllHotelAsync();
                if (hid != 0)
                {
                    Rooms = await _roomService.GetAllRoomAsync(hid);
                }
            }
            catch (Exception ex)
            {
                Hotels = new List<Models.Hotel>();
                ViewData["ErrorMessage"] = ex.Message;
            }
            return Page();
        }

        public async Task OnPostAsync(int hid)
        {
            Rooms = await _roomService.GetAllRoomAsync(hid);
            Hotels = await _hotelService.GetAllHotelAsync(); 
        }
    }
}

RazorHotelDB/Pages/Rooms/UpdateRoom.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB.Interfaces;
using RazorHotelDB.Models;

namespace RazorHotelDB.Pages.Rooms
{
    public class UpdateRoomModel : PageModel
    {
        private IRoomService _roomService;

        [BindProperty]
        public Room Room { get; set; }

        [BindProperty]
        public RoomType RoomType { get; set; }

        public UpdateRoomModel(IRoomService roomService)
        {
            _roomService = roomService;
        }
        public async Task OnGetAsync(int hid, int rid)
        {
            Room = await _roomService.GetRoomFromIdAsync(rid, hid);
        }

        public async Task<IActionResult> OnPostAsync(int hid, int rid)
        {
            Room.Types = RoomType.ToString()[0];
            await _roomService.UpdateRoomAsync(Room, rid, hid);
            return RedirectToPage("GetAllRooms");
        }
    }
}

RazorHotelDB/Pages/Rooms/CreateRoom.cshtml
@page
@using RazorHotelDB.Models
@model RazorHotelDB.Pages.Rooms.CreateRoomModel
@{
    ViewData["Title"] = "Create Room";
}
<h1>Create Room</h1>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="None " class="text-danger">
            </div>
            <div class="form-group">
                <label asp-for="@Model.Room.HotelNr" class="control-label"></label>
                <input asp-for="@Model.HotelNr" class="form-control" required/>
                <span asp-validation-for="@Model.Room.HotelNr" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <label asp-for="@Model.Room.RoomNr" class="control-label"></label>
                <input asp-for="@Model.Room.RoomNr" class="form-control" required/>
                <span asp-validation-for="@Model.Room.RoomNr" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <label asp-for="@Model.Room.Types" class="control-label"></label>
                <select asp-for="@Model.RoomType" asp-items="Html.GetEnumSelectList<RoomType>()" class="form-control" required>
                </select>
            </div>
            <p></p>
            <div class="form-group">
                <label asp-for="@Model.Room.Pris" class="control-label"></label>
                <input asp-for="@Model.Room.Pris" class="form-control" required/>
                <span asp-validation-for="@Model.Room.Pris" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <p></p>
        </form>
        <p>
            <a asp-page="/Rooms/GetAllRooms" asp-page-handler="MyRooms" asp-route-cid="@Model.HotelNr">Back to rooms in hotel</a>
        </p>
    </div>
</div>


@*<div class="@(Model.createResult ? "alert alert-warning": "alert alert-danger")" role="alert">
            @(Model.createResult ? "Oprettelse ok" : "Fejl i oprettelse")
        </div>
        @*Spørg Poul om Fejl i oprettelse*@

RazorHotelDB/Pages/Rooms/DeleteRoom.cshtml
@page
@model RazorHotelDB.Pages.Rooms.DeleteRoomModel
@{
    ViewData["Title"] = "Delte Room";
}

<h1>Room about to be deleted</h1>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.Room.RoomNr" />
            <div class="form-group">
                <label asp-for="@Model.Room.HotelNr" class="control-label"></label>
                <input asp-for="@Model.Room.HotelNr" class="form-control" />
            </div>
            <p></p>
            <div class="form-group">
                <label asp-for="@Model.Room.Types" class="control-label"></label>
                <input asp-for="@Model.Room.Types" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Room.Pris" class="control-label"></label>
                <input asp-for="@Model.Room.Pris" class="form-control" />
            </div>
            <p></p><p></p>
            <div class="formgroup">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
            <p></p>
        </form>
    </div>
    <div>
        <a asp-page="GetAllRooms">Cancel</a>
    </div>
</div>

RazorHotelDB/Pages/Rooms/GetAllRooms.cshtml
@page
@model RazorHotelDB.Pages.Rooms.GetAllRoomsModel
@using RazorHotelDB.Models
@{
    ViewData["Title"] = "GetAllRooms";
}
<h1>Get all Rooms </h1>



<h4>Rooms in Hotel nr. @Model.HotelNr - @Model.Navn</h4>
<p></p>


<form method="post">
    <div class="form-group">
        @*find a change for @Model.HotelNr below*@
        <label asp-for="@Model.HotelNr" class="custom-control-label"></label>
        <select name="hid">
            <option value="">Select a hotel</option>
            @foreach (Hotel item in @Model.Hotels)
            {
                <option value="@item.HotelNr">@item.Navn</option>
            }
        </select>
    </div>
    <p></p>
    <input type="submit" value="Rooms for hotel" />
</form>



@if (Model.Rooms != null && Model.Rooms.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Room Number</th>
                <th>Hotel Number</th>
                <th>Room Type</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var room in Model.Rooms)
            {
                <tr>
                    <td>@room.RoomNr</td>
                    <td>@room.HotelNr</td>
                    <td>@room.Types</td>
                    <td>@room.Pris</td>
                    <td>
                        <a asp-page="UpdateRoom" asp-route-hid="@room.HotelNr" asp-route-rid="@room.RoomNr">Update</a> |
                        <a asp-page="DeleteRoom" asp-route-hid="@room.HotelNr" asp-route-rid="@room.RoomNr">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

RazorHotelDB/Pages/Rooms/UpdateRoom.cshtml
@page
@using RazorHotelDB.Models
@model RazorHotelDB.Pages.Rooms.UpdateRoomModel
@{
    ViewData["Title"] = "Update Room";
}

<h1>Update the Room below</h1>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <input asp-for="@Model.Room.RoomNr" type="hidden" />
            <div class="form-group">
                <label asp-for="@Model.Room.RoomNr" class="control-label"></label>
                <input asp-for="@Model.Room.RoomNr" class="form-control" />
                <span asp-validation-for="Room.RoomNr" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <label asp-for="@Model.Room.HotelNr" class="control-label"></label>
                <input asp-for="@Model.Room.HotelNr" class="form-control" />
                <span asp-validation-for="Room.HotelNr" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <label asp-for="@Model.Room.Types" class="control-label"></label>
                <select asp-for="@Model.RoomType" asp-items="Html.GetEnumSelectList<RoomType>()" class="form-control">
                </select>
            </div>

            <p></p>
            <div class="form-group">
                <label asp-for="@Model.Room.Pris" class="control-label"></label>
                <input asp-for="@Model.Room.Pris" class="form-control" />
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Save updated Room" class="btn btn-primary" />
            </div>
            <p></p>
            <div class="formgroup">
                <input type="submit" value="Delete Room" asp-page-handler="Delete" class="btn btn-primary" />
            </div>
            <p></p>
            <div>
                <a asp-page="GetAllRooms">Cancel</a>
            </div>
        </form>
    </div>
</div>