RazorHotelDB/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorHotelDB.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorHotelDB/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorHotelDB.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public string UserName { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            UserName = HttpContext.Session.GetString("UserName");
            if (UserName == null)
            {
                return RedirectToPage("Login");
            }
            else
            {
                return Page();
            }
        }
    }
}

RazorHotelDB/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB.Interfaces;
using RazorHotelDB.Models;

namespace RazorHotelDB.Pages.Shared
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string UserName { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public string Message { get; set; }

        private IUserService _userService;

        public LoginModel(IUserService userService)
        {
            _userService = userService;
        }


        public void OnGet()
        {
        }

        public void OnGetLogout() {
            HttpContext.Session.Remove("UserName");
        }

        public IActionResult OnPost() {
            User loginUser = _userService.VerifyUser(UserName, Password);
            if (loginUser != null)
            {
                HttpContext.Session.SetString("UserName", loginUser.UserName);
                return RedirectToPage("Index");
            }
            else {
                Message = "Invalid Username or Password";
                UserName = "";
                Password = "";
                return Page();
            }
        }
    }
}

RazorHotelDB/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorHotelDB.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorHotelDB/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome @Model.UserName</h1>
</div>

<div class="text-center"> 
    <a asp-page="Login" asp-page-handler="Logout">Logout</a>
</div>

RazorHotelDB/Pages/Login.cshtml
@page
@model RazorHotelDB.Pages.Shared.LoginModel
@{
}
<h1>Please Login</h1>

@Model.Message
<form method="post">
    <table>
        <tr>
            <td>UserName</td>
            <td><Input type="text" asp-for="@Model.UserName"/></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><Input type="password" asp-for="@Model.Password"/></td>
        </tr>
        <tr>
            <td>&nbsp</td>
            <td><Input type="submit" value="Login"/></td>
        </tr>
    </table>
</form>